name: 'Pull r/UConnDorms'

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  pull:
    name: 'Pull r/UConnDorms'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install ts-node
      run: npm i -g typescript ts-node
    - name: Install dependencies
      run: npm install
    - name: Retrieve & Parse Data
      run: npm run generate-dorms
      env:
        CI_TOKEN: ${{ secrets.CI_TOKEN }}
        CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
        REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
        TARGET: UConnDorms
    - name: Sync with S3
      uses: zdurham/s3-upload-github-action@master
      with:
        args: --acl public-read
      env:
        FILE: ./UConnDorms.json
        S3_REGION: 'us-east-1'
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
        S3_KEY: UConnDorms.json
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}